version: "3.8"

services:
  mongodb:
    image: mongo
    container_name: mongodb_container
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - app_network

  nodejs:
    build:
      context: .
    container_name: book
    ports:
      - "5000:5000"
    networks:
      - app_network
    depends_on:
      - mongodb

volumes:
  mongodb_data:

networks:
  app_network:
